server:
  port: 80

spring:
  profiles:
    active: dev

mybatis-plus:
  type-handlers-package: com.wrp.blog.typeHandler
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: true
      logic-not-delete-value: false